name: build and deploy weather image to server

on:
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/weather:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/weather:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /opt/app
            sudo docker-compose pull && sudo docker-compose up -d --force-recreate
