name: upload my image to DockerHub

on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create docker image
        run: echo Hello, world!

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/weather:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/weather:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo docker stop weather
            sudo docker rm weather
            sudo docker rmi ${{ secrets.DOCKER_USER }}/weather
            sudo docker pull ${{ secrets.DOCKER_USER }}/weather
            sudo docker run --name weather -d -p 80:3000 ${{ secrets.DOCKER_USER }}/weather
